# Generated by Django 3.1.2 on 2020-10-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='company_ibn',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='company_id',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='company_abn',
            field=models.CharField(default='NULL', max_length=100, unique=True),
        ),
    ]
