# Generated by Django 3.1.2 on 2020-10-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20201010_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='company_abn',
            field=models.CharField(default=681239, max_length=100, unique=True),
        ),
    ]
