# Generated by Django 3.1.2 on 2020-10-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20201010_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='company_abn',
            field=models.IntegerField(unique=True),
        ),
    ]
