# Generated by Django 3.1.2 on 2020-10-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_companydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='company_abn',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
