# Generated by Django 3.1.2 on 2020-10-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20201010_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='KinawayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('main_contact', models.CharField(blank=True, max_length=1000, null=True)),
                ('operating_region', models.CharField(blank=True, max_length=1000, null=True)),
                ('company_abn', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
