# Generated by Django 3.1.2 on 2020-10-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_bbfdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='contacted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='intersected',
            field=models.IntegerField(default=0),
        ),
    ]
