# Generated by Django 3.1.2 on 2020-10-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20201011_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='data_from',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
